stages:
  - lint
  - test
  - weekly_tests
  - publish
  - docs

lint:
  image: python:3.7-buster
  stage: lint
  script:
    - python -m pip install --upgrade pip
    - pip install flake8
    - flake8 eoreader
  tags:
    - sertit
  except:
    - tags

# Test with data on local disk
pytest:
  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest
  stage: test
  variables:
    CI_EOREADER_USE_S3: "0"
  before_script:
    - python -m pip install --upgrade pip
    - pip install --ignore-installed PyYAML
    - pip install -e .
  script:
    - pytest -v --durations=0 --cov-report term --cov-report xml:cov.xml --cov=eoreader  --cov-config=.coveragerc CI/SCRIPTS
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  tags:
    - sertit
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - changes:
        - eoreader/**/*.{py,xml}

# Test with data on S3
# TODO: create S3-specific CI ?
pytest_s3:
  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install --ignore-installed PyYAML
    - pip install -e .
  script:
    - pytest -v --durations=0 --cov-report term --cov-report xml:cov.xml --cov=eoreader  --cov-config=.coveragerc CI/SCRIPTS
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  tags:
    - sertit
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - changes:
        - eoreader/**/*.{py,xml}

# Test SNAP with SNAP
pytest_all_sar_snap:
  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install --ignore-installed PyYAML
    - pip install -e .
  script:
    - pytest -v --durations=0 --cov-report term --cov-report xml:cov.xml --cov=eoreader  --cov-config=.coveragerc CI/SCRIPTS_SNAP/test_all_sar_snap.py
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  tags:
    - sertit
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "SNAP"'

tox-linux-3.7:on-schedule:
  image: docker.sertit.unistra.fr/sertit/eo-containers/python:3.7
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py37
  tags:
    - sertit
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'

tox-linux-3.8:on-schedule:
  image: docker.sertit.unistra.fr/sertit/eo-containers/python:3.8
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py38
  tags:
    - sertit
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'
  needs: [ "tox-linux-3.7:on-schedule" ]

tox-linux-3.9:on-schedule:
  image: docker.sertit.unistra.fr/sertit/eo-containers/python:3.9
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py39
  tags:
    - sertit
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'
  needs: [ "tox-linux-3.8:on-schedule" ]

tox-windows:on-schedule:
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox-conda.ini
  tags:
    - windows
    - conda
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'
  needs: [ "tox-linux-3.9:on-schedule" ]


tox-linux-3.7-snap:on-schedule:
  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox-snap.ini -e py37
  tags:
    - sertit
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "SNAP"'

upload_wheel:linux:
  image: python:3.7-buster
  stage: publish
  script:
    - pip install twine methodtools
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${PYPI_PWD} TWINE_USERNAME=${PYPI_TOKEN} python -m twine upload dist/*
  tags:
    - sertit
  only:
    - tags

#pages:
#  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest
#  stage: docs
#  script:
#    - python -m pip install --upgrade pip
#    - pip install -r requirements-doc.txt --ignore-installed PyYAML
#    - pip install mistune==0.8.4  # Workaround
#    - sphinx-build docs/ docs/_build/html/
#    - mv docs/_build/html/ public/
#  artifacts:
#    paths:
#      - public
#  tags:
#    - sertit
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'
#  needs: ["lint"]
