stages:
  - build
  - test
  - weekly_tests
  - publish
  - docs

lint:
  image: python:3.7-buster
  stage: build
  script:
    - python -m pip install --upgrade pip
    - pip install flake8
    - flake8 eoreader
  tags:
    - linux
  except:
    - tags

pytest:
  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest --cov-config=.coveragerc
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt --ignore-installed PyYAML
    - pip install -e .
  script:
    - pytest -v --durations=0 --cov-report term --cov-report xml:cov.xml --cov=eoreader CI/SCRIPTS
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  tags:
    - linux
  except:
    - tags

tox-linux-3.7:on-schedule:
  image: docker.sertit.unistra.fr/sertit/eo-containers/python:3.7
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py37
  tags:
    - linux
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'

tox-linux-3.8:on-schedule:
  image: docker.sertit.unistra.fr/sertit/eo-containers/python:3.8
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py38
  tags:
    - linux
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'

tox-linux-3.9:on-schedule:
  image: docker.sertit.unistra.fr/sertit/eo-containers/python:3.9
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py39
  tags:
    - linux
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'

tox-windows:on-schedule:
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox-conda.ini
  tags:
    - windows
    - conda
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'


tox-linux-3.7-snap:on-schedule:
  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox-snap.ini -e py37
  tags:
    - linux
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "SNAP"'

upload_wheel:linux:
  image: python:3.7-buster
  stage: publish
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${PYPI_PWD} TWINE_USERNAME=${PYPI_TOKEN} python -m twine upload dist/*
  tags:
    - linux
  only:
    - tags

pages:
  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest
  stage: docs
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements-doc.txt --ignore-installed PyYAML
    - sphinx-build docs/ docs/_build/html/
    - mv docs/_build/html/ public/
  artifacts:
    paths:
      - public
  tags:
    - linux
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'
