stages:
  - lint
  - test
  - weekly_tests
  - publish
  - docs

variables:
  EEO_DEPS: $REGISTRY_GITLAB/extracteo/extracteo_deps
  EO_CONTAINER: $REGISTRY_GITLAB/eo-containers/python

lint:
  image: python:3.7-buster
  stage: lint
  script:
    - python -m pip install --upgrade pip
    - pip install flake8
    - flake8 eoreader
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: always

# Test with data on local disk
pytest:
  image: $EEO_DEPS:latest
  stage: test
  variables:
    CI_EOREADER_USE_S3: "0"
  before_script:
    - python -m pip install --upgrade pip
    - pip install --ignore-installed PyYAML
    - pip install -e .
  script:
    - pytest -v --durations=0 --cov-report term --cov-report html:${CI_PROJECT_DIR}/cov_on_disk.html --cov=eoreader --cov-config=.coveragerc CI/SCRIPTS --log-cli-level DEBUG
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/cov_on_disk.html
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  tags:
    - sertit
    - linux
    - high_memory
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - changes:
        - eoreader/**/*.{py,xml}
        - CI/**/*.{py,xml}
        - .gitlab-ci.yml
        - pytest.ini
  needs: [ "lint" ]

# Test with data on S3
# TODO: create S3-specific CI ?
pytest_s3:
  image: $EEO_DEPS:latest
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install --ignore-installed PyYAML
    - pip install -e .
  script:
    - pytest -v --durations=0 --cov-report term --cov-report html:${CI_PROJECT_DIR}/cov_s3.html --cov=eoreader --cov-config=.coveragerc CI/SCRIPTS --log-cli-level DEBUG --capture=tee-sys
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/cov_s3.html
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  tags:
    - sertit
    - linux
    - high_memory
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - changes:
        - eoreader/**/*.{py,xml}
        - CI/**/*.{py,xml}
        - .gitlab-ci.yml
        - pytest.ini
  needs: [ "lint" ]

# Test SNAP with SNAP
pytest_end_to_end:
  image: $EEO_DEPS:latest
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install --ignore-installed PyYAML
    - pip install -e .
  script:
    - pytest -v --durations=0 --cov-report term --cov-report html:${CI_PROJECT_DIR}/cov_e2e.html --cov=eoreader  --cov-config=.coveragerc CI/SCRIPTS_SNAP/test_all_sat_end_to_end_on_disk.py --log-cli-level DEBUG --capture=tee-sys
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/cov_e2e.html
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  tags:
    - sertit
    - linux
    - high_memory
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "END_TO_END"'
      when: always
    - if: $CI_COMMIT_TAG
      when: always

tox-linux-3.7:on-schedule:
  image: $EO_CONTAINER:3.7
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py37
  tags:
    - sertit
    - linux
    - high_memory
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'

tox-linux-3.8:on-schedule:
  image: $EO_CONTAINER:3.8
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py38
  tags:
    - sertit
    - linux
    - high_memory
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'
  needs: [ "tox-linux-3.7:on-schedule" ]

tox-linux-3.9:on-schedule:
  image: $EO_CONTAINER:3.9
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -c tox.ini -e py39
  tags:
    - sertit
    - linux
    - high_memory
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'
  needs: [ "tox-linux-3.8:on-schedule" ]

tox-windows:on-schedule:
  stage: weekly_tests
  before_script:
    - pip install tox
  script:
    - tox -c tox-conda.ini -e py39
  tags:
    - sertit
    - windows
    - high_memory
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "WEEKLY"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "windows"'
      when: always
