name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:

jobs:
  lint:
    name: Linters (pre-commit)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Run pre-commit action
      uses: pre-commit/action@v2.0.0
